import { describe, it, expect } from 'bun:test'
import { sessionLabel, fmt } from './format'

describe('sessionLabel', () => {
  it('prefers the title when present', () => {
    expect(sessionLabel({ title: 'Fix login bug', first_prompt: 'whatever' })).toBe('Fix login bug')
  })

  it('trims the title', () => {
    expect(sessionLabel({ title: '  Spaced title  ' })).toBe('Spaced title')
  })

  it('falls back to the first prompt when there is no title', () => {
    expect(sessionLabel({ first_prompt: 'Refactor the parser' })).toBe('Refactor the parser')
  })

  it('strips local-command-caveat wrappers from the first-prompt fallback', () => {
    const fp = '<local-command-caveat>Caveat: generated by a local command. DO NOT respond</local-command-caveat>'
    expect(sessionLabel({ first_prompt: fp })).toBe('')
  })

  it('strips command-name wrappers and keeps the readable remainder', () => {
    const fp = '<command-name>/commit</command-name> please commit my work'
    expect(sessionLabel({ first_prompt: fp })).toBe('please commit my work')
  })

  it('collapses whitespace left behind by stripped tags', () => {
    const fp = '<command-message>x</command-message>   real    text'
    expect(sessionLabel({ first_prompt: fp })).toBe('real text')
  })

  it('returns an empty string when nothing usable is present', () => {
    expect(sessionLabel({})).toBe('')
    expect(sessionLabel({ title: '   ', first_prompt: '' })).toBe('')
  })
})

describe('fmt', () => {
  it('formats thousands with K', () => {
    expect(fmt(1_500)).toBe('1.5K')
  })

  it('formats millions with M', () => {
    expect(fmt(2_400_000)).toBe('2.4M')
  })

  it('formats billions with B rather than four-digit millions', () => {
    // 13_290_800_000 used to render as "13290.8M", which is unreadable at a glance.
    expect(fmt(13_290_800_000)).toBe('13.3B')
  })

  it('formats trillions with T', () => {
    expect(fmt(2_500_000_000_000)).toBe('2.5T')
  })

  it('leaves small numbers alone', () => {
    expect(fmt(942)).toBe('942')
  })
})
