import type { SessionMeta, HarnessId } from './types'

// ---------------------------------------------------------------------------
// TeamConfig — shared member configuration (single source of truth)
// ---------------------------------------------------------------------------

export interface TeamConfig {
  /** 'solo' = normal local-only behavior; 'member' = push metrics to a central */
  mode: 'solo' | 'member'
  /** Central base URL, e.g. "https://central.example:47291" (no trailing slash) */
  endpoint: string
  /** Org namespace used on the central server */
  org: string
  /** This developer's identity (name or email) */
  user: string
  /** Bearer token for the central ingest endpoint (never logged) */
  token: string
  /**
   * Member-side push interval preference in seconds. The effective interval
   * is max(centralPushIntervalSec, pushIntervalSec ?? 0), then clamped.
   * Absent or 0 means "use whatever central dictates".
   */
  pushIntervalSec?: number
}

export const DEFAULT_TEAM: TeamConfig = {
  mode: 'solo',
  endpoint: '',
  org: 'default',
  user: '',
  token: '',
}

// ---------------------------------------------------------------------------
// Push interval — central-controlled cadence (Phase 6)
// ---------------------------------------------------------------------------

/** Bounds and default for the push interval, in seconds. */
export const PUSH_INTERVAL = {
  MIN_SEC: 15,
  MAX_SEC: 3600,
  DEFAULT_SEC: 30,
} as const

/**
 * Clamp a push-interval value (seconds) to the allowed range.
 * Non-finite, NaN, or <= 0 values fall back to DEFAULT_SEC.
 * In-range values are rounded to the nearest second.
 */
export function clampPushInterval(sec: number): number {
  if (!Number.isFinite(sec) || sec <= 0) return PUSH_INTERVAL.DEFAULT_SEC
  const rounded = Math.round(sec)
  if (rounded < PUSH_INTERVAL.MIN_SEC) return PUSH_INTERVAL.MIN_SEC
  if (rounded > PUSH_INTERVAL.MAX_SEC) return PUSH_INTERVAL.MAX_SEC
  return rounded
}

/** Tag a session with its owning user (team mode). Pure — returns a new object. */
export function tagUser(session: SessionMeta, user: string): SessionMeta {
  return { ...session, user }
}

/** Distinct, sorted list of users present in a session list. Skips undefined. Pure. */
export function distinctUsers(sessions: SessionMeta[]): string[] {
  const set = new Set<string>()
  for (const s of sessions) if (s.user) set.add(s.user)
  return Array.from(set).sort()
}

/** Multi-select user predicate. Empty/undefined selection = all sessions pass.
 *  Sessions with no `user` are excluded when a selection is active. Pure. */
export function filterByUsers<T extends { user?: string }>(sessions: T[], users: string[]): T[] {
  if (!users || users.length === 0) return sessions
  const set = new Set(users)
  return sessions.filter(s => !!s.user && set.has(s.user))
}

/** Multi-select harness predicate. Empty/undefined selection = all sessions pass.
 *  Sessions with no `harness` field are treated as 'claude'. Pure. */
export function filterByHarnesses<T extends { harness?: HarnessId }>(sessions: T[], harnesses: HarnessId[]): T[] {
  if (!harnesses || harnesses.length === 0) return sessions
  const set = new Set(harnesses)
  return sessions.filter(s => set.has(s.harness ?? 'claude'))
}

// ---------------------------------------------------------------------------
// Phase 7 — reverse channel protocol types (member ↔ central WebSocket)
// ---------------------------------------------------------------------------

/**
 * Message sent from the central server to a connected member socket
 * to request on-demand chat history for a session.
 */
export interface AgentRequest {
  type: 'fetch-chat'
  /**
   * Correlation ID — matches the AgentResponse.id.
   * Generated by the central via crypto.randomUUID().
   */
  id: string
  /** The session ID to retrieve messages for. */
  sessionId: string
  /** Which AI harness owns this session. */
  harness: HarnessId
  /** Claude-only: encoded project directory needed to locate the .jsonl file. */
  encodedDir?: string
}

/**
 * Message sent from a member's WebSocket connection back to the central
 * in response to an AgentRequest.
 */
export interface AgentResponse {
  type: 'chat-result'
  /** Correlation ID — echoes AgentRequest.id. */
  id: string
  ok: boolean
  /**
   * Session messages when ok=true.
   * Shape matches the harness-specific *SessionMessage types but is typed as
   * unknown[] to avoid coupling the protocol to any specific reader type.
   */
  messages?: unknown[]
  error?: string
}
