/**
 * brand.ts — which drawing of the logo this page shows: the amber machine mark or the teal central.
 *
 * A central and a machine serve ONE bundle, so the choice cannot be made at build time. The server
 * marks the app shell of a central with `<html data-central="1">` (`central-branding.ts`), which is
 * readable synchronously on the very first render — before login, before any request — which is
 * exactly when the login screen and the loading splash draw the mark.
 *
 * The teal files are the same artwork with only the colour swapped, generated by
 * `scripts/gen-brand-assets.ts`. Never recolour the mark any other way (a CSS filter, a hue
 * rotation): the logo's geometry and colours are the owner's design.
 */

/** The in-app marks that have a teal central variant. */
export type BrandAsset = '/minimalistLogo.png' | '/logo.png' | '/logo-light.png'

const CENTRAL_VARIANT: Record<BrandAsset, string> = {
  '/minimalistLogo.png': '/minimalistLogo-central.png',
  '/logo.png': '/logo-central.png',
  '/logo-light.png': '/logo-light-central.png',
}

/** True when the page was served by a central. Pure over the attribute; false wherever it is absent. */
export function isCentralShell(root: { dataset?: DOMStringMap } | null | undefined =
  typeof document !== 'undefined' ? document.documentElement : undefined): boolean {
  return root?.dataset?.central === '1'
}

/** The path of `asset` in this page's identity. */
export function brandAsset(asset: BrandAsset, central: boolean = isCentralShell()): string {
  return central ? CENTRAL_VARIANT[asset] : asset
}
