/**
 * brand.ts — which drawing of the logo this page shows: the amber machine mark or the teal central.
 *
 * A central and a machine serve ONE bundle, so the choice cannot be made at build time. The server
 * marks the app shell of a central with `<html data-central="1">` (`central-branding.ts`), which is
 * readable synchronously on the very first render — before login, before any request — which is
 * exactly when the login screen and the loading splash draw the mark.
 *
 * The teal files are the same artwork with only the colour swapped, generated by
 * `scripts/gen-brand-assets.ts`. Never recolour the mark any other way (a CSS filter, a hue
 * rotation): the logo's geometry and colours are the owner's design.
 */

/**
 * `path` with a content tag: `/logo.png` -> `/logo.png?v=3f9a1c02`.
 *
 * The server keeps these images unhashed under stable URLs, and a browser holds whichever version it
 * fetched first — a rebranded logo went on showing the old one, and an installed PWA kept an icon
 * that had already been corrected. The tag is the hash of the file's own bytes (computed by
 * `vite.config.ts` and injected as `__BRAND_TAGS__`), so the URL changes exactly when the artwork
 * does. Where no tag is known (a unit test, an unlisted file) the path is returned untouched.
 */
declare const __BRAND_TAGS__: Record<string, string> | undefined
export function versionedAsset(path: string): string {
  const tags = typeof __BRAND_TAGS__ === 'undefined' ? undefined : __BRAND_TAGS__
  const tag = tags?.[path]
  return tag ? `${path}?v=${tag}` : path
}

/** The in-app marks that have a teal central variant. */
export type BrandAsset = '/minimalistLogo.png' | '/logo.png' | '/logo-light.png'

const CENTRAL_VARIANT: Record<BrandAsset, string> = {
  '/minimalistLogo.png': '/minimalistLogo-central.png',
  '/logo.png': '/logo-central.png',
  '/logo-light.png': '/logo-light-central.png',
}

/** True when the page was served by a central. Pure over the attribute; false wherever it is absent. */
export function isCentralShell(root: { dataset?: DOMStringMap } | null | undefined =
  typeof document !== 'undefined' ? document.documentElement : undefined): boolean {
  return root?.dataset?.central === '1'
}

/** The path of `asset` in this page's identity. */
export function brandAsset(asset: BrandAsset, central: boolean = isCentralShell()): string {
  return versionedAsset(central ? CENTRAL_VARIANT[asset] : asset)
}
