/**
 * monacoEntry.ts — THE Monaco entry this app loads, composed from the package's own published
 * subpaths instead of its `monaco-editor` barrel.
 *
 * **WHY THIS FILE EXISTS: the barrel costs 6.9 MB this product cannot use.** Monaco 0.56's
 * `languages/features/typescript/register` contains `new Worker(new URL('./ts.worker.js', ...))`,
 * a literal Vite recognises and resolves at BUILD time — so importing the barrel emits
 * `ts.worker-<hash>.js`, measured at 6,914,791 bytes, whether or not a browser ever fetches it.
 * This feature is a single-file viewer/editor: a TypeScript language service type-checks one file
 * with no program around it and reports confident errors for every import it cannot resolve, so the
 * feature was switched OFF in the design spec. The 6.9 MB was therefore pure dead weight — in
 * `dist/`, in `embedded-dist.generated.ts`, and in the compiled `agentop` binary every user
 * downloads.
 *
 * **`monaco-editor/<path>`, NOT `monaco-editor/esm/vs/<path>`.** The package's `exports` map is
 * `{"./*.js": "./esm/vs/*.js", "./*": "./esm/vs/*.js"}`, so the `esm/vs/` prefix every pre-0.5x
 * recipe still uses resolves to `esm/vs/esm/vs/...` and fails outright.
 *
 * **WHAT THIS COMPOSITION IS: `esm/vs/index.js` line for line, minus exactly three things.** It was
 * generated by reading that barrel and `features/register.all.js` off disk, not assembled from a
 * recipe, because anything the barrel imports and this file does not is a feature silently deleted
 * from the editor — and `monacoEntry.lint.test.ts` now asserts that set equality in both directions
 * against the installed package, with these three as its only NAMED exclusions. The three omissions:
 *
 * 1. `languages/features/typescript/register` — the TypeScript/JavaScript LANGUAGE SERVICE, and the
 *    whole point of the exercise. **Syntax highlighting is NOT affected**: that comes from the
 *    Monarch grammars under `languages/definitions/`, and `typescript` and `javascript` are both
 *    still registered below. What is given up is completion, hovers, rename, and diagnostics for
 *    `.ts`/`.js` — none of which this feature offers for any other language either.
 * 2. `lsp` (`esm/external/monaco-lsp-client`) — the barrel re-exports it, and it is UNREACHABLE
 *    through the `exports` map above (it lives outside `esm/vs/`). Nothing in this app uses it.
 * 3. `base/browser/ui/codicons/codicon/codicon-modifiers.css` — the one omission that changes
 *    NOTHING. `suggestWidget.js`, `codeActionMenu.js` and `standaloneGotoSymbolQuickAccess.js` each
 *    import it themselves and all three are registered below, so the stylesheet is in the bundle
 *    either way; naming it again would be the only hand-copied line here with no effect.
 *
 * Re-enabling TypeScript services later is one import and one `?worker` restored in
 * `monacoSetup.ts`; there is no build configuration to undo.
 *
 * **Do not hand-edit the lists below.** Regenerate them against the installed package whenever
 * monaco-editor is upgraded — a grammar added upstream is a language that silently loses its colour
 * here until it is added, which is exactly the failure mode this file's shape invites.
 */

// Every editor CONTRIBUTION the barrel registers — find, folding, suggest, the context menu,
// bracket matching, sticky scroll, the 60-odd others. `features/register.all` is the package's own
// roll-up of them and is a strict subset of the barrel's list; the imports after it are the rest.
import 'monaco-editor/features/register.all'

import 'monaco-editor/editor/browser/coreCommands'
import 'monaco-editor/editor/contrib/caretOperations/browser/caretOperations'
import 'monaco-editor/editor/contrib/dropOrPasteInto/browser/copyPasteContribution'
import 'monaco-editor/editor/contrib/find/browser/findController'
import 'monaco-editor/editor/contrib/gotoSymbol/browser/goToCommands'
import 'monaco-editor/editor/contrib/gotoError/browser/markerSelectionStatus'
import 'monaco-editor/editor/contrib/semanticTokens/browser/documentSemanticTokens'
import 'monaco-editor/editor/contrib/suggest/browser/suggestController'
import 'monaco-editor/editor/common/standaloneStrings'

// The Monarch GRAMMARS — syntax highlighting, one directory per language, all 81 of them
// enumerated from `node_modules/monaco-editor/esm/vs/languages/definitions/`.
import 'monaco-editor/languages/definitions/abap/register'
import 'monaco-editor/languages/definitions/apex/register'
import 'monaco-editor/languages/definitions/azcli/register'
import 'monaco-editor/languages/definitions/bat/register'
import 'monaco-editor/languages/definitions/bicep/register'
import 'monaco-editor/languages/definitions/cameligo/register'
import 'monaco-editor/languages/definitions/clojure/register'
import 'monaco-editor/languages/definitions/coffee/register'
import 'monaco-editor/languages/definitions/cpp/register'
import 'monaco-editor/languages/definitions/csharp/register'
import 'monaco-editor/languages/definitions/csp/register'
import 'monaco-editor/languages/definitions/css/register'
import 'monaco-editor/languages/definitions/cypher/register'
import 'monaco-editor/languages/definitions/dart/register'
import 'monaco-editor/languages/definitions/dockerfile/register'
import 'monaco-editor/languages/definitions/ecl/register'
import 'monaco-editor/languages/definitions/elixir/register'
import 'monaco-editor/languages/definitions/flow9/register'
import 'monaco-editor/languages/definitions/freemarker2/register'
import 'monaco-editor/languages/definitions/fsharp/register'
import 'monaco-editor/languages/definitions/go/register'
import 'monaco-editor/languages/definitions/graphql/register'
import 'monaco-editor/languages/definitions/handlebars/register'
import 'monaco-editor/languages/definitions/hcl/register'
import 'monaco-editor/languages/definitions/html/register'
import 'monaco-editor/languages/definitions/ini/register'
import 'monaco-editor/languages/definitions/java/register'
import 'monaco-editor/languages/definitions/javascript/register'
import 'monaco-editor/languages/definitions/julia/register'
import 'monaco-editor/languages/definitions/kotlin/register'
import 'monaco-editor/languages/definitions/less/register'
import 'monaco-editor/languages/definitions/lexon/register'
import 'monaco-editor/languages/definitions/liquid/register'
import 'monaco-editor/languages/definitions/lua/register'
import 'monaco-editor/languages/definitions/m3/register'
import 'monaco-editor/languages/definitions/markdown/register'
import 'monaco-editor/languages/definitions/mdx/register'
import 'monaco-editor/languages/definitions/mips/register'
import 'monaco-editor/languages/definitions/msdax/register'
import 'monaco-editor/languages/definitions/mysql/register'
import 'monaco-editor/languages/definitions/objective-c/register'
import 'monaco-editor/languages/definitions/pascal/register'
import 'monaco-editor/languages/definitions/pascaligo/register'
import 'monaco-editor/languages/definitions/perl/register'
import 'monaco-editor/languages/definitions/pgsql/register'
import 'monaco-editor/languages/definitions/php/register'
import 'monaco-editor/languages/definitions/pla/register'
import 'monaco-editor/languages/definitions/postiats/register'
import 'monaco-editor/languages/definitions/powerquery/register'
import 'monaco-editor/languages/definitions/powershell/register'
import 'monaco-editor/languages/definitions/protobuf/register'
import 'monaco-editor/languages/definitions/pug/register'
import 'monaco-editor/languages/definitions/python/register'
import 'monaco-editor/languages/definitions/qsharp/register'
import 'monaco-editor/languages/definitions/r/register'
import 'monaco-editor/languages/definitions/razor/register'
import 'monaco-editor/languages/definitions/redis/register'
import 'monaco-editor/languages/definitions/redshift/register'
import 'monaco-editor/languages/definitions/restructuredtext/register'
import 'monaco-editor/languages/definitions/ruby/register'
import 'monaco-editor/languages/definitions/rust/register'
import 'monaco-editor/languages/definitions/sb/register'
import 'monaco-editor/languages/definitions/scala/register'
import 'monaco-editor/languages/definitions/scheme/register'
import 'monaco-editor/languages/definitions/scss/register'
import 'monaco-editor/languages/definitions/shell/register'
import 'monaco-editor/languages/definitions/solidity/register'
import 'monaco-editor/languages/definitions/sophia/register'
import 'monaco-editor/languages/definitions/sparql/register'
import 'monaco-editor/languages/definitions/sql/register'
import 'monaco-editor/languages/definitions/st/register'
import 'monaco-editor/languages/definitions/swift/register'
import 'monaco-editor/languages/definitions/systemverilog/register'
import 'monaco-editor/languages/definitions/tcl/register'
import 'monaco-editor/languages/definitions/twig/register'
import 'monaco-editor/languages/definitions/typescript/register'
import 'monaco-editor/languages/definitions/typespec/register'
import 'monaco-editor/languages/definitions/vb/register'
import 'monaco-editor/languages/definitions/wgsl/register'
import 'monaco-editor/languages/definitions/xml/register'
import 'monaco-editor/languages/definitions/yaml/register'

// The three LANGUAGE SERVICES kept: each is a worker-backed completion/diagnostics provider, and
// each has a worker wired in `monacoSetup.ts`. `typescript` is deliberately absent — see the header.
export * as css from 'monaco-editor/languages/features/css/register'
export * as html from 'monaco-editor/languages/features/html/register'
export * as json from 'monaco-editor/languages/features/json/register'

export * from 'monaco-editor/editor/editor.api'
