#!/usr/bin/env bun
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  type Tool,
} from "@modelcontextprotocol/sdk/types.js";

const API = process.env.AGENTISTICS_API ?? "http://localhost:47291";

// Minimal pricing table — mirrors src/lib/types.ts MODEL_PRICING
const PRICES: Record<string, { input: number; output: number; cacheRead: number; cacheWrite: number }> = {
  "claude-opus-4":     { input: 15,   output: 75,   cacheRead: 1.50,  cacheWrite: 18.75 },
  "claude-sonnet-4":   { input: 3,    output: 15,   cacheRead: 0.30,  cacheWrite: 3.75  },
  "claude-haiku-4":    { input: 0.80, output: 4,    cacheRead: 0.08,  cacheWrite: 1.00  },
  "claude-3-5-sonnet": { input: 3,    output: 15,   cacheRead: 0.30,  cacheWrite: 3.75  },
  "claude-3-5-haiku":  { input: 0.80, output: 4,    cacheRead: 0.08,  cacheWrite: 1.00  },
  "claude-3-opus":     { input: 15,   output: 75,   cacheRead: 1.50,  cacheWrite: 18.75 },
};
const FALLBACK_PRICE = { input: 3, output: 15, cacheRead: 0.30, cacheWrite: 3.75 };

function getPrice(modelId: string) {
  if (!modelId) return FALLBACK_PRICE;
  const key = Object.keys(PRICES).find(k => modelId.toLowerCase().includes(k));
  return key ? PRICES[key]! : FALLBACK_PRICE;
}

function calcCostUSD(input: number, output: number, cacheRead: number, cacheWrite: number, model: string): number {
  const p = getPrice(model);
  return (input * p.input + output * p.output + cacheRead * p.cacheRead + cacheWrite * p.cacheWrite) / 1_000_000;
}

// Static mirror of src/lib/componentCatalog.tsx — keep in sync when adding components
const CATALOG = [
  // KPI cards
  { id: "kpi.messages",        label: "Messages",           category: "kpi",      defaultW: 3,  defaultH: 3, minW: 2, minH: 2, description: "Total message count in selected period" },
  { id: "kpi.sessions",        label: "Sessions",           category: "kpi",      defaultW: 3,  defaultH: 3, minW: 2, minH: 2, description: "Session count + avg msgs/session" },
  { id: "kpi.tool-calls",      label: "Tool calls",         category: "kpi",      defaultW: 3,  defaultH: 3, minW: 2, minH: 2, description: "Total tool execution count" },
  { id: "kpi.cost",            label: "Estimated cost",     category: "kpi",      defaultW: 3,  defaultH: 3, minW: 2, minH: 2, description: "Estimated USD cost" },
  { id: "kpi.streak",          label: "Streak",             category: "kpi",      defaultW: 3,  defaultH: 3, minW: 2, minH: 2, description: "Consecutive days streak" },
  { id: "kpi.longest-session", label: "Longest session",    category: "kpi",      defaultW: 3,  defaultH: 3, minW: 2, minH: 2, description: "Duration of longest session" },
  { id: "kpi.commits",         label: "Commits",            category: "kpi",      defaultW: 3,  defaultH: 3, minW: 2, minH: 2, description: "Git commits via Claude" },
  { id: "kpi.files",           label: "Files modified",     category: "kpi",      defaultW: 3,  defaultH: 3, minW: 2, minH: 2, description: "Files modified + line diff" },
  { id: "kpi.input-tokens",    label: "Input tokens",       category: "kpi",      defaultW: 3,  defaultH: 3, minW: 2, minH: 2, description: "Input tokens sent to model" },
  { id: "kpi.output-tokens",   label: "Output tokens",      category: "kpi",      defaultW: 3,  defaultH: 3, minW: 2, minH: 2, description: "Output tokens generated by model" },
  // Activity
  { id: "activity.chart",          label: "Activity chart (full)",       category: "activity", defaultW: 8,  defaultH: 7, minW: 4, minH: 4, description: "Full activity chart with all metrics" },
  { id: "activity.chart.messages", label: "Activity — Messages only",    category: "activity", defaultW: 6,  defaultH: 6, minW: 3, minH: 3, description: "Daily messages bar chart" },
  { id: "activity.chart.sessions", label: "Activity — Sessions only",    category: "activity", defaultW: 6,  defaultH: 6, minW: 3, minH: 3, description: "Daily sessions bar chart" },
  { id: "activity.chart.tools",    label: "Activity — Tool calls only",  category: "activity", defaultW: 6,  defaultH: 6, minW: 3, minH: 3, description: "Daily tool calls bar chart" },
  { id: "activity.chart.overlay",  label: "Activity — Overlay",          category: "activity", defaultW: 8,  defaultH: 6, minW: 4, minH: 3, description: "Overlay visualization of all metrics" },
  { id: "activity.heatmap",        label: "Activity heatmap",            category: "activity", defaultW: 6,  defaultH: 6, minW: 3, minH: 3, description: "Calendar heatmap of daily activity" },
  { id: "activity.hours",          label: "Usage by hour",               category: "activity", defaultW: 8,  defaultH: 6, minW: 4, minH: 3, description: "Hourly usage breakdown" },
  // Costs
  { id: "costs.models", label: "Model usage",        category: "costs",    defaultW: 12, defaultH: 7, minW: 6, minH: 4, description: "Cost and token breakdown by model" },
  { id: "costs.budget", label: "Budget & forecast",  category: "costs",    defaultW: 6,  defaultH: 7, minW: 4, minH: 4, description: "Monthly budget progress and cost forecast" },
  { id: "costs.cache",  label: "Cache efficiency",   category: "costs",    defaultW: 6,  defaultH: 7, minW: 4, minH: 4, description: "Cache hit rate and savings" },
  // Projects
  { id: "projects.top",       label: "Top projects", category: "projects", defaultW: 7,  defaultH: 7, minW: 4, minH: 4, description: "Most active projects ranked by metrics" },
  { id: "projects.languages", label: "Languages",    category: "projects", defaultW: 5,  defaultH: 6, minW: 3, minH: 3, description: "Language distribution word cloud" },
  // Tools & Agents
  { id: "tools.metrics",        label: "Tool metrics (full)",        category: "tools", defaultW: 12, defaultH: 8, minW: 6, minH: 4, description: "Full breakdown of tool usage by type" },
  { id: "tools.metrics.calls",  label: "Tool metrics — calls only",  category: "tools", defaultW: 8,  defaultH: 7, minW: 4, minH: 4, description: "Tool call counts chart" },
  { id: "tools.metrics.tokens", label: "Tool metrics — tokens only", category: "tools", defaultW: 8,  defaultH: 7, minW: 4, minH: 4, description: "Tokens consumed per tool type" },
  { id: "tools.agents",         label: "Agent metrics",              category: "tools", defaultW: 12, defaultH: 8, minW: 6, minH: 4, description: "Sub-agent invocation metrics, durations, costs" },
  // Sessions
  { id: "sessions.highlights", label: "Highlights",       category: "sessions", defaultW: 12, defaultH: 6, minW: 6, minH: 3, description: "Record-breaking sessions" },
  { id: "sessions.recent",     label: "Recent sessions",  category: "sessions", defaultW: 12, defaultH: 7, minW: 6, minH: 4, description: "List of most recent sessions" },
];

async function apiGet(path: string) {
  const res = await fetch(`${API}${path}`);
  if (!res.ok) throw new Error(`agentistics API ${path} → HTTP ${res.status}`);
  return res.json();
}

async function getPrefs() {
  return apiGet("/api/preferences");
}

async function putPrefs(patch: Record<string, unknown>) {
  const res = await fetch(`${API}/api/preferences`, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(patch),
  });
  if (!res.ok) throw new Error(`PUT /api/preferences → HTTP ${res.status}`);
  return res.json();
}

function nextId(items: Array<{ i: string }>): string {
  let max = 0;
  for (const item of items) {
    const n = parseInt(item.i, 10);
    if (!isNaN(n) && n > max) max = n;
  }
  return String(max + 1);
}

// First-fit shelf packing across a 12-column grid.
// Scans every y level from 0 downward and returns the leftmost x where
// an item of width `newW` fits without overlapping existing items.
function autoPosition(
  items: Array<{ x: number; y: number; w: number; h: number }>,
  newW = 3,
  gridW = 12,
): { x: number; y: number } {
  if (items.length === 0) return { x: 0, y: 0 };
  const maxBottom = Math.max(...items.map((i) => i.y + i.h));
  for (let y = 0; y <= maxBottom; y++) {
    // Occupied x-ranges at this y level
    const blocks = items
      .filter((i) => i.y <= y && i.y + i.h > y)
      .map((i) => ({ start: i.x, end: i.x + i.w }))
      .sort((a, b) => a.start - b.start);
    // Find leftmost gap >= newW
    let x = 0;
    for (const block of blocks) {
      if (block.start >= x + newW) break; // gap before this block fits
      if (block.end > x) x = block.end;
    }
    if (x + newW <= gridW) return { x, y };
  }
  // No gap found — place at bottom
  return { x: 0, y: maxBottom };
}

// After packing, extend any item that has empty space to its right
// (no neighbour sharing any row with it on the right side).
// This eliminates orphaned gaps like a w:8 chart next to 4 empty columns.
function fillGaps(
  items: Array<{ x: number; y: number; w: number; h: number }>,
  gridW = 12,
): void {
  for (const item of items) {
    const rightEdge = item.x + item.w;
    if (rightEdge >= gridW) continue;
    const hasRightNeighbour = items.some(
      (other) =>
        other !== item &&
        other.x >= rightEdge &&
        other.y < item.y + item.h &&
        other.y + other.h > item.y,
    );
    if (!hasRightNeighbour) {
      item.w = gridW - item.x;
    }
  }
}

// ─── Server ─────────────────────────────────────────────────────────────────

const server = new Server(
  { name: "agentistics", version: "1.0.0" },
  { capabilities: { tools: {} } },
);

const TOOLS: Tool[] = [
  {
    name: "agentistics_summary",
    description:
      "Get an overview of Claude Code usage metrics: total tokens, estimated cost, sessions, streak, most used model, and top project. Good starting point for any metrics question.",
    inputSchema: { type: "object", properties: {}, required: [] },
  },
  {
    name: "agentistics_projects",
    description:
      "List all Claude Code projects with session counts, message counts, token usage, estimated cost, and last active date.",
    inputSchema: { type: "object", properties: {}, required: [] },
  },
  {
    name: "agentistics_sessions",
    description:
      "Get the most recent Claude Code sessions with project path, duration, message count, token usage, and model.",
    inputSchema: {
      type: "object",
      properties: {
        limit: {
          type: "number",
          description: "Max sessions to return (default 20, max 50)",
        },
      },
    },
  },
  {
    name: "agentistics_costs",
    description:
      "Get cost breakdown by model: token counts (input/output/cache read/write) and estimated USD cost per model.",
    inputSchema: { type: "object", properties: {}, required: [] },
  },
  {
    name: "agentistics_component_catalog",
    description:
      "List all components available for the custom layout page, with IDs, categories, descriptions, and default grid sizes. Call this before building or modifying a layout.",
    inputSchema: {
      type: "object",
      properties: {
        category: {
          type: "string",
          description:
            "Filter by category: kpi, activity, costs, projects, tools, sessions",
        },
      },
    },
  },
  {
    name: "agentistics_get_layouts",
    description:
      "Get all custom layouts: names, components in each, which is active, and each component's instance ID for removal.",
    inputSchema: { type: "object", properties: {}, required: [] },
  },
  {
    name: "agentistics_create_layout",
    description: "Create a new empty named layout on the custom page.",
    inputSchema: {
      type: "object",
      properties: {
        name: { type: "string", description: "Name for the new layout" },
      },
      required: ["name"],
    },
  },
  {
    name: "agentistics_add_component",
    description:
      "Add a single component to a layout. Use agentistics_component_catalog to get valid componentId values. Positioned automatically at the bottom of the grid unless x/y are given.",
    inputSchema: {
      type: "object",
      properties: {
        layoutName: {
          type: "string",
          description:
            "Target layout name. Omit to use the currently active layout.",
        },
        componentId: {
          type: "string",
          description:
            "Component ID from the catalog (e.g. 'kpi.cost', 'activity.chart')",
        },
        x: {
          type: "number",
          description: "Column (0–11). Optional — auto-placed if omitted.",
        },
        y: {
          type: "number",
          description: "Row. Optional — auto-placed if omitted.",
        },
        w: {
          type: "number",
          description: "Width in grid units (1–12). Optional — uses default.",
        },
        h: {
          type: "number",
          description: "Height in grid units. Optional — uses default.",
        },
      },
      required: ["componentId"],
    },
  },
  {
    name: "agentistics_remove_component",
    description:
      "Remove a component from a layout by its instance ID (the 'instanceId' field from agentistics_get_layouts).",
    inputSchema: {
      type: "object",
      properties: {
        layoutName: {
          type: "string",
          description: "Layout name. Omit to use the active layout.",
        },
        itemId: {
          type: "string",
          description: "Instance ID of the item to remove",
        },
      },
      required: ["itemId"],
    },
  },
  {
    name: "agentistics_set_active_layout",
    description: "Switch the active layout shown on the /custom page.",
    inputSchema: {
      type: "object",
      properties: {
        name: { type: "string", description: "Name of the layout to activate" },
      },
      required: ["name"],
    },
  },
  {
    name: "agentistics_delete_layout",
    description: "Delete a named layout. Cannot delete the last remaining layout.",
    inputSchema: {
      type: "object",
      properties: {
        name: { type: "string", description: "Name of the layout to delete" },
      },
      required: ["name"],
    },
  },
  {
    name: "agentistics_export_pdf",
    description:
      "Generate a PDF report of Claude Code usage. Returns a URL that, when opened in a browser, automatically opens the PDF export modal pre-configured with the requested options. The user can review settings and click Download to save the PDF.",
    inputSchema: {
      type: "object",
      properties: {
        range: {
          type: "string",
          enum: ["7d", "30d", "90d", "all"],
          description: "Date range for the report (default: all)",
        },
      },
    },
  },
  {
    name: "agentistics_build_layout",
    description:
      "Build a complete layout in one call: creates it, adds all requested components with auto-positioning, and optionally activates it. Ideal for setting up a themed dashboard from scratch.",
    inputSchema: {
      type: "object",
      properties: {
        name: { type: "string", description: "Name for the layout" },
        componentIds: {
          type: "array",
          items: { type: "string" },
          description: "Ordered array of component IDs to add",
        },
        activate: {
          type: "boolean",
          description:
            "Set as active layout after building (default true)",
        },
      },
      required: ["name", "componentIds"],
    },
  },
];

server.setRequestHandler(ListToolsRequestSchema, async () => ({ tools: TOOLS }));

server.setRequestHandler(CallToolRequestSchema, async (req) => {
  const { name, arguments: args } = req.params;

  try {
    switch (name) {
      case "agentistics_summary": {
        const data = await apiGet("/api/data");
        const sc = data.statsCache ?? {};
        const totals = sc.allTimeTotals ?? {};
        const models = sc.modelUsage ?? {};
        const topModel =
          Object.entries(models as Record<string, { totalTokens?: number }>)
            .sort(([, a], [, b]) => (b.totalTokens ?? 0) - (a.totalTokens ?? 0))[0]?.[0] ?? "—";
        const projects = (data.projects ?? []) as Array<{ name: string; sessions?: Array<unknown> }>;
        const topProject =
          [...projects]
            .sort((a, b) => (b.sessions?.length ?? 0) - (a.sessions?.length ?? 0))[0]?.name ?? "—";

        // Aggregate from sessions for accurate totals (statsCache may be stale or empty)
        const allSessions = (data.sessions ?? []) as Array<any>;
        let totalCostUSD = 0;
        let totalInput = 0, totalOutput = 0, totalCacheRead = 0, totalCacheWrite = 0;
        for (const s of allSessions) {
          const inp = s.input_tokens ?? 0;
          const out = s.output_tokens ?? 0;
          const cr  = s.cache_read_input_tokens ?? 0;
          const cw  = s.cache_creation_input_tokens ?? 0;
          totalInput    += inp;
          totalOutput   += out;
          totalCacheRead  += cr;
          totalCacheWrite += cw;
          totalCostUSD  += calcCostUSD(inp, out, cr, cw, s.model ?? "");
        }
        // Fall back to statsCache if sessions carry no token data
        const finalInput       = totalInput    || (totals.inputTokens      ?? 0);
        const finalOutput      = totalOutput   || (totals.outputTokens     ?? 0);
        const finalCacheRead   = totalCacheRead  || (totals.cacheReadTokens  ?? 0);
        const finalCacheWrite  = totalCacheWrite || (totals.cacheWriteTokens ?? 0);

        return {
          content: [{
            type: "text",
            text: JSON.stringify({
              totalInputTokens:      finalInput,
              totalOutputTokens:     finalOutput,
              totalCacheReadTokens:  finalCacheRead,
              totalCacheWriteTokens: finalCacheWrite,
              estimatedCostUSD:      Math.round(totalCostUSD * 100) / 100,
              totalSessions: allSessions.length,
              totalProjects: projects.length,
              topModel,
              topProject,
              activeDays: sc.activeDays ?? 0,
              currentStreak: sc.currentStreak ?? 0,
            }, null, 2),
          }],
        };
      }

      case "agentistics_projects": {
        const data = await apiGet("/api/data");
        // projects[] only has {name, path, sessions:[{sessionId}]} — aggregate tokens/cost from sessions
        const allSessions = (data.sessions ?? []) as Array<any>;
        const byPath: Record<string, { inputTokens: number; outputTokens: number; cacheRead: number; cacheWrite: number; costUSD: number; messages: number; lastActive: string; languages: string[] }> = {};
        for (const s of allSessions) {
          const key = s.project_path as string;
          if (!key) continue;
          if (!byPath[key]) byPath[key] = { inputTokens: 0, outputTokens: 0, cacheRead: 0, cacheWrite: 0, costUSD: 0, messages: 0, lastActive: "", languages: [] };
          const agg = byPath[key]!;
          const inp = s.input_tokens ?? 0;
          const out = s.output_tokens ?? 0;
          const cr  = s.cache_read_input_tokens ?? 0;
          const cw  = s.cache_creation_input_tokens ?? 0;
          agg.inputTokens  += inp;
          agg.outputTokens += out;
          agg.cacheRead    += cr;
          agg.cacheWrite   += cw;
          agg.costUSD      += calcCostUSD(inp, out, cr, cw, s.model ?? "");
          agg.messages     += (s.user_message_count ?? 0) + (s.assistant_message_count ?? 0);
          if (!agg.lastActive || (s.start_time ?? "") > agg.lastActive) agg.lastActive = s.start_time ?? "";
          for (const lang of s.languages ?? []) if (!agg.languages.includes(lang)) agg.languages.push(lang);
        }
        const projects = (data.projects ?? []) as Array<any>;
        const summary = projects
          .map((p: any) => {
            const agg = byPath[p.path] ?? { inputTokens: 0, outputTokens: 0, cacheRead: 0, cacheWrite: 0, costUSD: 0, messages: 0, lastActive: "", languages: [] };
            return {
              name: p.name,
              path: p.path,
              sessions: (p.sessions ?? []).length,
              messages: agg.messages,
              inputTokens: agg.inputTokens,
              outputTokens: agg.outputTokens,
              totalTokens: agg.inputTokens + agg.outputTokens,
              estimatedCostUSD: Math.round(agg.costUSD * 10000) / 10000,
              lastActive: agg.lastActive || null,
              languages: agg.languages,
            };
          })
          .sort((a: any, b: any) => b.totalTokens - a.totalTokens);
        return { content: [{ type: "text", text: JSON.stringify(summary, null, 2) }] };
      }

      case "agentistics_sessions": {
        const limit = Math.min((args as any)?.limit ?? 20, 50);
        const data = await apiGet("/api/data");
        const rows = ((data.sessions ?? []) as Array<any>)
          .slice(0, limit)
          .map((s: any) => {
            const inp = s.input_tokens ?? 0;
            const out = s.output_tokens ?? 0;
            const cr  = s.cache_read_input_tokens ?? 0;
            const cw  = s.cache_creation_input_tokens ?? 0;
            return {
              id: s.session_id,
              project: s.project_path,
              startedAt: s.start_time,
              durationMinutes: s.duration_minutes,
              messages: (s.user_message_count ?? 0) + (s.assistant_message_count ?? 0),
              inputTokens: inp,
              outputTokens: out,
              cacheReadTokens: cr,
              cacheWriteTokens: cw,
              totalTokens: inp + out + cr + cw,
              estimatedCostUSD: Math.round(calcCostUSD(inp, out, cr, cw, s.model ?? "") * 10000) / 10000,
              model: s.model ?? null,
            };
          });
        return { content: [{ type: "text", text: JSON.stringify(rows, null, 2) }] };
      }

      case "agentistics_costs": {
        const data = await apiGet("/api/data");
        const usage = (data.statsCache?.modelUsage ?? {}) as Record<string, any>;
        const breakdown = Object.entries(usage)
          .map(([model, u]: [string, any]) => ({
            model,
            inputTokens: u.inputTokens ?? 0,
            outputTokens: u.outputTokens ?? 0,
            cacheReadTokens: u.cacheReadTokens ?? 0,
            cacheWriteTokens: u.cacheWriteTokens ?? 0,
            totalTokens: u.totalTokens ?? 0,
            estimatedCostUSD: u.costUSD ?? 0,
          }))
          .sort((a, b) => b.totalTokens - a.totalTokens);
        return { content: [{ type: "text", text: JSON.stringify(breakdown, null, 2) }] };
      }

      case "agentistics_component_catalog": {
        const category = (args as any)?.category as string | undefined;
        const items = category
          ? CATALOG.filter((c) => c.category === category)
          : CATALOG;
        return { content: [{ type: "text", text: JSON.stringify(items, null, 2) }] };
      }

      case "agentistics_get_layouts": {
        const prefs = await getPrefs();
        const layouts = (prefs.layouts ?? {}) as Record<string, Array<any>>;
        const active = (prefs.activeLayout ?? "") as string;
        const summary = Object.entries(layouts).map(([layoutName, items]) => ({
          name: layoutName,
          isActive: layoutName === active,
          componentCount: items.length,
          components: items.map((item: any) => ({
            instanceId: item.i,
            componentId: item.componentId,
            x: item.x,
            y: item.y,
            w: item.w,
            h: item.h,
          })),
        }));
        return {
          content: [{
            type: "text",
            text: JSON.stringify({ activeLayout: active, layouts: summary }, null, 2),
          }],
        };
      }

      case "agentistics_create_layout": {
        const layoutName = (args as any).name as string;
        const prefs = await getPrefs();
        const layouts = { ...(prefs.layouts ?? {}) } as Record<string, Array<any>>;
        if (layouts[layoutName]) {
          return { content: [{ type: "text", text: `Layout "${layoutName}" already exists.` }] };
        }
        layouts[layoutName] = [];
        await putPrefs({ layouts, activeLayout: prefs.activeLayout });
        return { content: [{ type: "text", text: `Layout "${layoutName}" created.` }] };
      }

      case "agentistics_add_component": {
        const a = args as any;
        const prefs = await getPrefs();
        const layouts = { ...(prefs.layouts ?? {}) } as Record<string, Array<any>>;
        const targetName = (a.layoutName ?? prefs.activeLayout ?? "") as string;

        if (!targetName) throw new Error("No active layout. Create one first with agentistics_create_layout.");
        if (!layouts[targetName]) throw new Error(`Layout "${targetName}" not found.`);

        const catalogItem = CATALOG.find((c) => c.id === a.componentId);
        if (!catalogItem) throw new Error(`Unknown componentId "${a.componentId}". Use agentistics_component_catalog to list valid IDs.`);

        const current = layouts[targetName];
        const pos =
          a.x !== undefined && a.y !== undefined
            ? { x: a.x as number, y: a.y as number }
            : autoPosition(current, (a.w as number | undefined) ?? catalogItem.defaultW);

        const newItem = {
          i: nextId(current),
          componentId: a.componentId,
          x: pos.x,
          y: pos.y,
          w: (a.w as number | undefined) ?? catalogItem.defaultW,
          h: (a.h as number | undefined) ?? catalogItem.defaultH,
          minW: catalogItem.minW,
          minH: catalogItem.minH,
        };

        layouts[targetName] = [...current, newItem];
        await putPrefs({ layouts });
        return {
          content: [{
            type: "text",
            text: `Added "${a.componentId}" to layout "${targetName}" at (${newItem.x}, ${newItem.y}), size ${newItem.w}×${newItem.h}. Instance ID: ${newItem.i}`,
          }],
        };
      }

      case "agentistics_remove_component": {
        const a = args as any;
        const prefs = await getPrefs();
        const layouts = { ...(prefs.layouts ?? {}) } as Record<string, Array<any>>;
        const targetName = (a.layoutName ?? prefs.activeLayout ?? "") as string;

        if (!targetName || !layouts[targetName]) throw new Error(`Layout "${targetName}" not found.`);

        const before = layouts[targetName].length;
        layouts[targetName] = layouts[targetName].filter((item: any) => item.i !== a.itemId);

        if (layouts[targetName].length === before) {
          return { content: [{ type: "text", text: `Item "${a.itemId}" not found in layout "${targetName}".` }] };
        }

        await putPrefs({ layouts });
        return { content: [{ type: "text", text: `Removed item "${a.itemId}" from layout "${targetName}".` }] };
      }

      case "agentistics_set_active_layout": {
        const layoutName = (args as any).name as string;
        const prefs = await getPrefs();
        const layouts = (prefs.layouts ?? {}) as Record<string, unknown>;
        if (!layouts[layoutName]) {
          throw new Error(`Layout "${layoutName}" not found. Available: ${Object.keys(layouts).join(", ")}`);
        }
        await putPrefs({ activeLayout: layoutName });
        return { content: [{ type: "text", text: `Active layout set to "${layoutName}".` }] };
      }

      case "agentistics_delete_layout": {
        const layoutName = (args as any).name as string;
        const prefs = await getPrefs();
        const layouts = { ...(prefs.layouts ?? {}) } as Record<string, Array<any>>;

        if (!layouts[layoutName]) throw new Error(`Layout "${layoutName}" not found.`);
        if (Object.keys(layouts).length === 1) throw new Error("Cannot delete the last remaining layout.");

        delete layouts[layoutName];
        let active = (prefs.activeLayout ?? "") as string;
        if (active === layoutName) active = Object.keys(layouts)[0] ?? "";
        await putPrefs({ layouts, activeLayout: active });
        return {
          content: [{
            type: "text",
            text: `Deleted layout "${layoutName}". Active layout is now "${active}".`,
          }],
        };
      }

      case "agentistics_export_pdf": {
        const a = args as any;
        const range = (a?.range as string | undefined) ?? "all";
        const uiBase = API.replace(/:\d+$/, ":47292");
        const params = new URLSearchParams({ export: "pdf" });
        if (range !== "all") params.set("range", range);
        const url = `${uiBase}/?${params.toString()}`;
        const rangeLabel = range === "all" ? "all-time" : `last ${range}`;
        return {
          content: [{
            type: "text",
            text: `[⬇ Download PDF — ${rangeLabel}](pdf:${url})`,
          }],
        };
      }

      case "agentistics_build_layout": {
        const a = args as any;
        const layoutName = a.name as string;
        const componentIds = a.componentIds as string[];
        const activate = (a.activate as boolean | undefined) !== false;

        for (const id of componentIds) {
          if (!CATALOG.find((c) => c.id === id)) {
            throw new Error(`Unknown componentId "${id}". Use agentistics_component_catalog to list valid IDs.`);
          }
        }

        const prefs = await getPrefs();
        const layouts = { ...(prefs.layouts ?? {}) } as Record<string, Array<any>>;

        const items: Array<any> = [];
        for (const componentId of componentIds) {
          const cat = CATALOG.find((c) => c.id === componentId)!;
          const pos = autoPosition(items, cat.defaultW);
          items.push({
            i: nextId(items),
            componentId,
            x: pos.x,
            y: pos.y,
            w: cat.defaultW,
            h: cat.defaultH,
            minW: cat.minW,
            minH: cat.minH,
          });
        }
        fillGaps(items);

        layouts[layoutName] = items;
        const patch: Record<string, unknown> = { layouts };
        if (activate) patch.activeLayout = layoutName;
        await putPrefs(patch);

        return {
          content: [{
            type: "text",
            text: `Layout "${layoutName}" built with ${items.length} components: ${componentIds.join(", ")}${activate ? ". Now active." : "."}`,
          }],
        };
      }

      default:
        throw new Error(`Unknown tool: ${name}`);
    }
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    return {
      content: [{ type: "text", text: `Error: ${message}` }],
      isError: true,
    };
  }
});

const transport = new StdioServerTransport();
await server.connect(transport);