import React from 'react'
import { useOutletContext } from 'react-router-dom'
import { format } from 'date-fns'
import {
  MessageSquare, Zap, Clock, Flame, GitCommit,
  Wrench, FileCode, TrendingUp, BarChart2,
  Download, Upload, Trophy, Bot, Target,
  Calendar,
} from 'lucide-react'
import type { AppContext } from '../lib/app-context'
import { formatProjectName } from '../lib/types'
import { fmt, fmtFull, fmtDuration, fmtCost } from '../lib/format'
import { Section } from '../components/Section'
import { StatCard } from '../components/StatCard'
import { HighlightsBoard } from '../components/HighlightsBoard'
import { ActivityChart } from '../components/ActivityChart'
import { ActivityHeatmap } from '../components/ActivityHeatmap'
import { HourChart } from '../components/HourChart'
import { ModelBreakdown } from '../components/ModelBreakdown'
import { BudgetPanel } from '../components/BudgetPanel'
import { CacheHitRatePanel } from '../components/CacheHitRatePanel'
import { ProjectsList } from '../components/ProjectsList'
import { TagCloud } from '../components/TagCloud'
import { ToolMetricsPanel } from '../components/ToolMetricsPanel'
import { AgentMetricsPanel } from '../components/AgentMetricsPanel'
import { RecentSessions } from '../components/RecentSessions'
import { StreakBreakdownButton } from '../components/StreakBreakdownButton'

type CardId = 'messages' | 'sessions' | 'tool-calls' | 'input-tokens' | 'output-tokens' | 'cost' | 'streak' | 'longest-session' | 'commits' | 'files'

export default function HomePage() {
  const ctx = useOutletContext<AppContext>()
  const {
    data, derived, statsCache, filters, setFilters,
    lang, theme, currency, setCurrency, brlRate,
    monthlyBudgetUSD, updateBudget,
    totalInputTokens, totalOutputTokens,
    setExpandedChart, setSelectedSession, setInfoModalIndex,
    infoItems, cardOrder,
    cardPrecision, setCardPrecision,
  } = ctx
  const d = derived

  function renderCard(id: CardId) {
    const fullKey = `kpi.${id}`
    const full = cardPrecision[fullKey] ?? false
    const toggleFull = () => setCardPrecision(fullKey, !full)
    const tog = (rawVal: number) => rawVal >= 1000 ? toggleFull : undefined

    let card: React.ReactNode = null
    if (id === 'messages') {
      card = <StatCard lang={lang} label={lang === 'pt' ? 'Mensagens' : 'Messages'} value={full ? fmtFull(d.totalMessages) : fmt(d.totalMessages)} sub={lang === 'pt' ? 'no período selecionado' : 'in selected period'} icon={<MessageSquare size={15} />} accent="var(--anthropic-orange)" info={infoItems[0]} onInfoClick={() => setInfoModalIndex(0)} fullPrecision={full} onTogglePrecision={tog(d.totalMessages)} />
    } else if (id === 'sessions') {
      card = <StatCard lang={lang} label={lang === 'pt' ? 'Sessões' : 'Sessions'} value={full ? fmtFull(d.totalSessions) : fmt(d.totalSessions)} sub={`avg ${d.totalSessions > 0 ? Math.round(d.totalMessages / d.totalSessions) : 0} msgs/sessão`} icon={<Zap size={15} />} accent="var(--accent-blue)" info={infoItems[1]} onInfoClick={() => setInfoModalIndex(1)} fullPrecision={full} onTogglePrecision={tog(d.totalSessions)} />
    } else if (id === 'tool-calls') {
      card = <StatCard lang={lang} label={lang === 'pt' ? 'Tool calls' : 'Tool calls'} value={full ? fmtFull(d.totalToolCalls) : fmt(d.totalToolCalls)} sub={lang === 'pt' ? 'execuções totais' : 'total executions'} icon={<Wrench size={15} />} accent="var(--accent-green)" info={infoItems[2]} onInfoClick={() => setInfoModalIndex(2)} fullPrecision={full} onTogglePrecision={tog(d.totalToolCalls)} />
    } else if (id === 'input-tokens') {
      card = <StatCard lang={lang} label={lang === 'pt' ? 'Tokens entrada' : 'Input tokens'} value={full ? fmtFull(totalInputTokens) : fmt(totalInputTokens)} sub={lang === 'pt' ? 'tokens enviados ao modelo' : 'tokens sent to model'} icon={<Download size={15} />} accent="var(--accent-blue)" info={infoItems[8]} onInfoClick={() => setInfoModalIndex(8)} fullPrecision={full} onTogglePrecision={tog(totalInputTokens)} />
    } else if (id === 'output-tokens') {
      card = <StatCard lang={lang} label={lang === 'pt' ? 'Tokens saída' : 'Output tokens'} value={full ? fmtFull(totalOutputTokens) : fmt(totalOutputTokens)} sub={lang === 'pt' ? 'tokens gerados pelo modelo' : 'tokens generated by model'} icon={<Upload size={15} />} accent="var(--accent-purple)" info={infoItems[9]} onInfoClick={() => setInfoModalIndex(9)} fullPrecision={full} onTogglePrecision={tog(totalOutputTokens)} />
    } else if (id === 'cost') {
      card = (
        <StatCard label={lang === 'pt' ? 'Custo estimado' : 'Est. cost'} value={fmtCost(d.totalCostUSD, currency, brlRate)} sub={lang === 'pt' ? 'preços da API Anthropic · não é assinatura' : 'Anthropic API pricing · not subscription'} icon={<TrendingUp size={15} />} accent="var(--anthropic-orange)" info={infoItems[5]} onInfoClick={() => setInfoModalIndex(5)}
          action={
            <button onClick={() => setCurrency(currency === 'USD' ? 'BRL' : 'USD')} style={{ fontSize: 10, fontWeight: 700, padding: '2px 6px', borderRadius: 4, border: '1px solid var(--border)', background: 'transparent', color: 'var(--text-tertiary)', cursor: 'pointer', fontFamily: 'inherit', transition: 'all 0.15s', letterSpacing: '0.03em' }} title={currency === 'USD' ? 'Switch to BRL (R$)' : 'Switch to USD'}>
              {currency}
            </button>
          }
        />
      )
    } else if (id === 'streak') {
      card = <StatCard label={lang === 'pt' ? 'Sequência' : 'Streak'} value={`${d.streak}d`} sub={lang === 'pt' ? 'dias consecutivos' : 'consecutive days'} icon={<Flame size={15} />} accent="#ef4444" info={infoItems[3]} onInfoClick={() => setInfoModalIndex(3)}
        action={d.projectStreaks && d.projectStreaks.length >= 1 && filters.projects.length !== 1 ? <StreakBreakdownButton items={d.projectStreaks} pt={lang === 'pt'} /> : undefined}
      />
    } else if (id === 'longest-session') {
      card = (
        <StatCard label={lang === 'pt' ? 'Sessão mais longa' : 'Longest session'} value={d.longestSession?.duration_minutes ? fmtDuration(d.longestSession.duration_minutes * 60_000) : '—'}
          sub={d.longestSession ? (() => {
            const msgs = (d.longestSession!.user_message_count ?? 0) + (d.longestSession!.assistant_message_count ?? 0)
            const msgStr = `${msgs} ${lang === 'pt' ? 'mensagens' : 'messages'}`
            if (filters.projects.length === 0 && d.longestSession!.project_path)
              return `${msgStr} · ${formatProjectName(d.longestSession!.project_path)}`
            return msgStr
          })() : ''}
          icon={<Clock size={15} />} accent="var(--accent-purple)" info={infoItems[4]} onInfoClick={() => setInfoModalIndex(4)} />
      )
    } else if (id === 'commits') {
      card = <StatCard label={lang === 'pt' ? 'Commits' : 'Commits'} value={d.gitCommits} sub={d.gitPushes > 0 ? `${d.gitPushes} ${lang === 'pt' ? 'pushes via Claude' : 'pushes via Claude'}` : lang === 'pt' ? 'via chamadas Bash do Claude' : 'via Claude Bash calls'} icon={<GitCommit size={15} />} accent="var(--accent-cyan)" info={infoItems[6]} onInfoClick={() => setInfoModalIndex(6)} />
    } else if (id === 'files') {
      card = <StatCard label={lang === 'pt' ? 'Arquivos' : 'Files'} value={d.filesModified} sub={d.linesAdded + d.linesRemoved > 0 ? `+${fmt(d.linesAdded)} / -${fmt(d.linesRemoved)} linhas` : lang === 'pt' ? 'via chamadas Bash do Claude' : 'via Claude Bash calls'} icon={<FileCode size={15} />} accent="var(--accent-green)" info={infoItems[7]} onInfoClick={() => setInfoModalIndex(7)} />
    }

    return (
      <div
        key={id}
        data-flash-id={id}
        style={{ position: 'relative', display: 'flex', flexDirection: 'column' }}
      >
        {card}
      </div>
    )
  }

  return (
    <>
      {/* Session date range */}
      {derived.firstSessionDate && derived.lastSessionDate && (
        <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, color: 'var(--text-tertiary)', flexWrap: 'wrap' }}>
          <Calendar size={12} style={{ flexShrink: 0, opacity: 0.6 }} />
          <span style={{ fontSize: 11, opacity: 0.7 }}>{lang === 'pt' ? '1ª sessão' : 'first session'}</span>
          <span style={{ color: 'var(--text-secondary)', fontWeight: 500, fontVariantNumeric: 'tabular-nums' }}>{format(derived.firstSessionDate, 'MMM d, yyyy')}</span>
          <span style={{ opacity: 0.4 }}>→</span>
          <span style={{ fontSize: 11, opacity: 0.7 }}>{lang === 'pt' ? 'última sessão' : 'last session'}</span>
          <span style={{ color: 'var(--text-secondary)', fontWeight: 500, fontVariantNumeric: 'tabular-nums' }}>{format(derived.lastSessionDate, 'MMM d, yyyy')}</span>
          <span style={{ opacity: 0.3, margin: '0 2px' }}>·</span>
          <span><strong style={{ color: 'var(--text-secondary)', fontWeight: 600 }}>{derived.sessionSpanDays.toLocaleString()}</strong> {lang === 'pt' ? 'dias' : 'days'}</span>
        </div>
      )}

      {/* KPI Cards grid */}
      <style>{`
        @keyframes liveFlash {
          0%   { box-shadow: 0 0 0 2px rgba(217,119,6,0.55), 0 0 14px rgba(217,119,6,0.12); }
          60%  { box-shadow: 0 0 0 2px rgba(217,119,6,0.18), 0 0 6px rgba(217,119,6,0.04); }
          100% { box-shadow: 0 0 0 0px rgba(217,119,6,0); }
        }
        .live-flash { animation: liveFlash 1.2s ease-out forwards; border-radius: var(--radius-lg); }
      `}</style>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: 12 }}>
        {(cardOrder as CardId[]).map(id => renderCard(id))}
      </div>

      {/* Highlights */}
      <Section flashId="highlights" title={<><Trophy size={14} /> {lang === 'pt' ? 'Recordes' : 'Highlights'}</>}>
        <HighlightsBoard sessions={derived.filteredSessions} projects={data.projects as any} lang={lang} />
      </Section>

      {/* Activity + Heatmap */}
      <div style={{ display: 'grid', gridTemplateColumns: '3fr 2fr', gap: 16, alignItems: 'stretch' }}>
        <Section flashId="activity" style={{ height: '100%' }} title={<><BarChart2 size={14} /> {lang === 'pt' ? 'Atividade ao longo do tempo' : 'Activity over time'}</>} onExpand={() => setExpandedChart('activity')}>
          <ActivityChart data={derived.heatmapData} theme={theme} />
        </Section>
        <Section flashId="heatmap" style={{ height: '100%' }} title={lang === 'pt' ? 'Heatmap de atividade' : 'Activity heatmap'} onExpand={() => setExpandedChart('heatmap')}>
          <ActivityHeatmap data={derived.heatmapData} />
        </Section>
      </div>

      {/* Hour distribution */}
      <Section flashId="hours" title={lang === 'pt' ? 'Uso por hora do dia' : 'Usage by hour'} onExpand={() => setExpandedChart('hours')}>
        <HourChart hourCounts={derived.hourCounts} hourMeta={derived.hourMeta} />
      </Section>

      {/* Model usage */}
      <Section flashId="models" title={<><TrendingUp size={14} /> {lang === 'pt' ? 'Uso por modelo' : 'Model usage & cost'}</>} onExpand={() => setExpandedChart('models')}>
        <ModelBreakdown
          modelUsage={derived.modelUsage}
          currency={currency}
          brlRate={brlRate}
          fallbackInputTokens={filters.projects.length > 0 ? derived.inputTokens : undefined}
          fallbackOutputTokens={filters.projects.length > 0 ? derived.outputTokens : undefined}
          fallbackCostUSD={filters.projects.length > 0 ? derived.totalCostUSD : undefined}
          note={
            filters.projects.length > 0
              ? (lang === 'pt'
                ? '* Custo e tokens estimados via taxa ponderada — sessões não registram o modelo utilizado individualmente.'
                : '* Cost and tokens estimated via blended rate — sessions do not record the model used individually.')
              : (filters.dateRange !== 'all' || filters.customStart || filters.customEnd
                ? (lang === 'pt'
                  ? '* Valores aproximados: tokens rateados pelo total diário. Proporção input/output baseada no histórico global.'
                  : '* Approximate values: tokens prorated from daily totals. Input/output split based on global historical ratio.')
                : undefined)
          }
        />
      </Section>

      {/* Budget */}
      <Section flashId="budget" title={<><Target size={14} /> {lang === 'pt' ? 'Orçamento & projeção' : 'Budget & forecast'}</>}>
        <BudgetPanel statsCache={statsCache} budgetUSD={monthlyBudgetUSD} onBudgetChange={updateBudget} currency={currency} brlRate={brlRate} lang={lang} />
      </Section>

      {/* Cache — full width */}
      <Section flashId="cache" title={<><Zap size={14} /> {lang === 'pt' ? 'Eficiência de cache' : 'Cache efficiency'}</>}>
        <CacheHitRatePanel hitRate={derived.cacheHitRate} cacheTotals={derived.cacheTotals} grossSavedUSD={derived.cacheGrossSavedUSD} writeOverheadUSD={derived.cacheWriteOverheadUSD} netSavedUSD={derived.cacheNetSavedUSD} perModel={derived.cachePerModel} currency={currency} brlRate={brlRate} lang={lang} />
      </Section>

      {/* Projects + Languages */}
      <div style={{ display: 'grid', gridTemplateColumns: '3fr 2fr', gap: 16, alignItems: 'stretch' }}>
        <Section flashId="projects" style={{ height: '100%' }} title={<><FileCode size={14} /> {lang === 'pt' ? 'Principais projetos' : 'Top projects'}</>}
          action={filters.projects.length > 0 ? (
            <button onClick={() => setFilters(f => ({ ...f, projects: [] }))} style={{ fontSize: 11, color: 'var(--text-tertiary)', background: 'transparent', border: 'none', cursor: 'pointer', fontFamily: 'inherit' }}>
              {lang === 'pt' ? 'Limpar' : 'Clear'}
            </button>
          ) : null}
        >
          <ProjectsList projectStats={derived.projectStats} onFilter={path => setFilters(f => ({ ...f, projects: [path] }))} />
        </Section>
        <Section title={<><FileCode size={14} /> {lang === 'pt' ? 'Linguagens' : 'Languages'}</>} style={{ height: '100%' }}>
          <TagCloud data={derived.langCounts} color="var(--accent-blue)" />
        </Section>
      </div>

      {/* Tool metrics */}
      <Section flashId="tools" title={<><Wrench size={14} /> {lang === 'pt' ? 'Métricas de ferramentas' : 'Tool metrics'}</>}>
        <ToolMetricsPanel toolCounts={derived.toolCounts} toolOutputTokens={derived.toolOutputTokens} agentFileReads={derived.agentFileReads} lang={lang} />
      </Section>

      {/* Agent metrics */}
      <Section flashId="agents" title={<><Bot size={14} /> {lang === 'pt' ? 'Métricas de agentes' : 'Agent metrics'}</>}>
        <AgentMetricsPanel invocations={derived.agentInvocations} agentTypeBreakdown={derived.agentTypeBreakdown} totalInvocations={derived.totalAgentInvocations} totalTokens={derived.totalAgentTokens} totalCostUSD={derived.totalAgentCostUSD} totalDurationMs={derived.totalAgentDurationMs} currency={currency} brlRate={brlRate} lang={lang} />
      </Section>

      {/* Recent sessions */}
      <Section flashId="sessions-list" title={<><Clock size={14} /> {lang === 'pt' ? 'Sessões recentes' : 'Recent sessions'}</>}>
        <RecentSessions sessions={derived.filteredSessions} lang={lang} onSelect={setSelectedSession} />
      </Section>
    </>
  )
}
