/**
 * central-branding.ts — PURE rewrites that give a central its own installed-app identity.
 *
 * A central and a machine run the same bundle, so installing the PWA of each produced two
 * dock entries with the identical amber icon and the identical name — indistinguishable.
 * The manifest is what the browser reads at install time, so the branding has to be applied
 * when it is SERVED (the central is a runtime mode, not a separate build).
 *
 * Both functions are total: anything unexpected in the input is returned unchanged, because a
 * cosmetic rewrite must never be able to break the app shell or the manifest.
 */

export const CENTRAL_APP_NAME = 'Agentistics Central'
/** Teal — the one hue that still reads as "not the amber one" at 32px in a dock. */
export const CENTRAL_THEME_COLOR = '#06B6D4'

/** Icon paths, machine → central. Generated by `packages/web/scripts/gen-central-icons.py`. */
const ICON_SWAPS: [string, string][] = [
  ['/icons/icon-192.png', '/icons/icon-central-192.png'],
  ['/icons/icon-512.png', '/icons/icon-central-512.png'],
  ['/favicon.ico', '/favicon-central.ico'],
]

/** Rewrite the web app manifest: name, theme colour and icon set. */
export function centralManifest(json: string): string {
  let m: Record<string, unknown>
  try {
    m = JSON.parse(json)
  } catch {
    return json
  }
  if (!m || typeof m !== 'object') return json

  m.name = CENTRAL_APP_NAME
  m.short_name = CENTRAL_APP_NAME
  m.description = 'Aggregated analytics for a team of AI coding assistants'
  m.theme_color = CENTRAL_THEME_COLOR
  if (Array.isArray(m.icons)) {
    m.icons = m.icons.map(icon => {
      if (!icon || typeof icon !== 'object') return icon
      const src = (icon as { src?: unknown }).src
      if (typeof src !== 'string') return icon
      const swap = ICON_SWAPS.find(([from]) => src === from)
      return swap ? { ...icon, src: swap[1] } : icon
    })
  }
  return JSON.stringify(m)
}

/** Rewrite the app shell: title, iOS home-screen name, touch icon, favicon, theme colour. */
export function centralHtml(html: string): string {
  let out = html
  for (const [from, to] of ICON_SWAPS) out = out.split(from).join(to)
  out = out.replace(/<title>[^<]*<\/title>/, `<title>${CENTRAL_APP_NAME}</title>`)
  // iOS reads this for the home-screen label; it is NOT covered by the manifest.
  out = out.replace(
    /(<meta\s+name="apple-mobile-web-app-title"\s+content=")[^"]*(")/,
    `$1${CENTRAL_APP_NAME}$2`,
  )
  out = out.replace(
    /(<meta\s+name="theme-color"\s+content=")[^"]*(")/,
    `$1${CENTRAL_THEME_COLOR}$2`,
  )
  return out
}
