/**
 * central-branding.ts — PURE rewrites that give a central its own installed-app identity.
 *
 * A central and a machine run the same bundle, so installing the PWA of each produced two
 * dock entries with the identical amber icon and the identical name — indistinguishable.
 * The manifest is what the browser reads at install time, so the branding has to be applied
 * when it is SERVED (the central is a runtime mode, not a separate build).
 *
 * Both functions are total: anything unexpected in the input is returned unchanged, because a
 * cosmetic rewrite must never be able to break the app shell or the manifest.
 */

export const CENTRAL_APP_NAME = 'Agentistics Central'
/** Teal — the one hue that still reads as "not the amber one" at 32px in a dock. */
export const CENTRAL_THEME_COLOR = '#06B6D4'

/** Icon paths, machine → central. Generated by `packages/web/scripts/gen-brand-assets.ts`. */
const ICON_SWAPS: [string, string][] = [
  ['/icons/icon-192.png', '/icons/icon-central-192.png'],
  ['/icons/icon-512.png', '/icons/icon-central-512.png'],
  ['/favicon.ico', '/favicon-central.ico'],
  ['/apple-touch-icon.png', '/apple-touch-icon-central.png'],
  // Android draws the MASKABLE icon on its home screen; left out, an installed central there was
  // the amber machine icon. (`/icons/icon-192.png` is not a substring of these, so order is free.)
  ['/icons/icon-192-maskable.png', '/icons/icon-central-192-maskable.png'],
  ['/icons/icon-512-maskable.png', '/icons/icon-central-512-maskable.png'],
]

/** The brand amber, as the source SVGs and the preboot splash write it. */
const MACHINE_ACCENT = '#FD8924'

/**
 * Set on `<html>` so the web bundle can tell, synchronously and before any request, that it is
 * being served by a central (`web/src/lib/brand.ts`). The in-app marks are `<img>`s inside the
 * JS bundle, which this rewrite never sees — they pick their teal variant off this attribute.
 */
export const CENTRAL_HTML_ATTR = 'data-central'

/** Rewrite the web app manifest: name, theme colour and icon set. */
export function centralManifest(json: string): string {
  let m: Record<string, unknown>
  try {
    m = JSON.parse(json)
  } catch {
    return json
  }
  if (!m || typeof m !== 'object') return json

  m.name = CENTRAL_APP_NAME
  m.short_name = CENTRAL_APP_NAME
  m.description = 'Aggregated analytics for a team of AI coding assistants'
  m.theme_color = CENTRAL_THEME_COLOR
  if (Array.isArray(m.icons)) {
    m.icons = m.icons.map(icon => {
      if (!icon || typeof icon !== 'object') return icon
      const src = (icon as { src?: unknown }).src
      if (typeof src !== 'string') return icon
      // The icon URL carries a `?v=<hash>` so a browser that cached an older drawing fetches the new
      // one; the swap is decided on the PATH and the query rides along.
      const q = src.indexOf('?')
      const path = q === -1 ? src : src.slice(0, q)
      const swap = ICON_SWAPS.find(([from]) => path === from)
      return swap ? { ...icon, src: swap[1] + (q === -1 ? '' : src.slice(q)) } : icon
    })
  }
  return JSON.stringify(m)
}

/** Rewrite the app shell: title, iOS home-screen name, touch icon, favicon, theme colour. */
export function centralHtml(html: string): string {
  let out = html
  for (const [from, to] of ICON_SWAPS) out = out.split(from).join(to)
  out = out.replace(/<title>[^<]*<\/title>/, `<title>${CENTRAL_APP_NAME}</title>`)
  // iOS reads this for the home-screen label; it is NOT covered by the manifest.
  out = out.replace(
    /(<meta\s+name="apple-mobile-web-app-title"\s+content=")[^"]*(")/,
    `$1${CENTRAL_APP_NAME}$2`,
  )
  out = out.replace(
    /(<meta\s+name="theme-color"\s+content=")[^"]*(")/,
    `$1${CENTRAL_THEME_COLOR}$2`,
  )
  // The preboot splash is an inline SVG in the shell — the first thing a central shows, and it was
  // the amber mark. Recoloured inside that one element only, never across the whole document.
  out = out.replace(/<svg class="ag-preboot-mark"[\s\S]*?<\/svg>/, svg => svg.split(MACHINE_ACCENT).join(CENTRAL_THEME_COLOR))
  // Only the app shell (it holds `#root`) is marked — anything else passes through untouched.
  if (out.includes('id="root"') && !out.includes(`${CENTRAL_HTML_ATTR}=`)) out = out.replace(/<html(\s|>)/, `<html ${CENTRAL_HTML_ATTR}="1"$1`)
  return out
}
