/**
 * cli-central.ts — the `agentop central …` command handler.
 *
 * Two paths, chosen automatically:
 *
 *  1. REPO path — when a `central.sh` is found in the agentistics checkout (dev, or running
 *     `agentop central` from inside the repo). We just shell out to that script, inheriting
 *     stdio so its interactive prompts and log streaming work naturally. Behavior unchanged.
 *
 *  2. STANDALONE path — the compiled binary run from ANY directory, with no repo present.
 *     We can't build the image from source, so we materialize a small Docker Compose that
 *     PULLS the published central image (ghcr.io/blpsoares/agentistics:<version>) into
 *     ~/.agentistics/central/, generate central.env interactively on first run, and drive
 *     `docker compose` directly — no repo, no clone required.
 */

import { existsSync } from 'fs'
import { mkdir, writeFile, chmod } from 'fs/promises'
import { randomBytes } from 'crypto'
import { homedir } from 'os'
import { join, resolve } from 'path'
import { version as APP_VERSION } from '../../../package.json'
import { input, confirm, select } from './cli-ui'

/** The central.sh subcommands this handler forwards / implements. */
export const CENTRAL_ACTIONS = ['up', 'init', 'down', 'logs', 'status', 'restart', 'pull'] as const
export type CentralAction = (typeof CENTRAL_ACTIONS)[number]

export function isCentralAction(value: string): value is CentralAction {
  return (CENTRAL_ACTIONS as readonly string[]).includes(value)
}

/** Published central image. The tag defaults to this binary's version so the central matches
 *  the CLI; override with AGENTISTICS_IMAGE (e.g. to pin :latest or a specific build). */
const IMAGE = process.env.AGENTISTICS_IMAGE || `ghcr.io/blpsoares/agentistics:${APP_VERSION}`
const PROJECT = process.env.PROJECT || 'team-mode'
const STANDALONE_DIR = join(homedir(), '.agentistics', 'central')

/**
 * Best-effort repo root that contains central.sh.
 *
 * ASSUMPTION: this file lives at `<repoRoot>/packages/server/server/cli-central.ts`,
 * so the repo root is three directories up from `import.meta.dir`. When running
 * from the compiled binary that path won't hold central.sh; the CWD is tried as
 * a fallback so `agentop central …` works when invoked from a checkout.
 */
function findCentralScript(): string | null {
  const candidates: string[] = []
  try {
    candidates.push(resolve(import.meta.dir, '..', '..', '..', 'central.sh'))
  } catch { /* import.meta.dir unavailable — skip */ }
  candidates.push(resolve(process.cwd(), 'central.sh'))
  for (const c of candidates) {
    if (existsSync(c)) return c
  }
  return null
}

/**
 * Run `bash <repoRoot>/central.sh <action> ...extraArgs`, inheriting stdio so
 * interactive prompts and log streaming pass through. Returns the child's exit code.
 */
async function runCentralRepo(script: string, action: string, extraArgs: string[]): Promise<number> {
  try {
    const proc = Bun.spawn(['bash', script, action, ...extraArgs], {
      stdin: 'inherit',
      stdout: 'inherit',
      stderr: 'inherit',
    })
    return await proc.exited
  } catch (err) {
    process.stderr.write(
      `Could not run central.sh: ${err instanceof Error ? err.message : String(err)}\n`,
    )
    return 1
  }
}

/**
 * Dispatch a central action. Uses the repo's central.sh when present (unchanged behavior),
 * otherwise falls back to the standalone Docker-image path so it works from anywhere.
 */
export async function runCentral(action: string, extraArgs: string[]): Promise<number> {
  if (!isCentralAction(action)) {
    process.stderr.write(
      `Invalid central action: ${action}. Expected one of: ${CENTRAL_ACTIONS.join(', ')}.\n`,
    )
    return 1
  }

  const script = findCentralScript()
  if (script) return runCentralRepo(script, action, extraArgs)
  return runCentralStandalone(action)
}

// ---------------------------------------------------------------------------
// Standalone path — no repo, pull the published image
// ---------------------------------------------------------------------------

/** Compose file that PULLS the published image instead of building from source. Host harness
 *  dirs are intentionally NOT mounted here (self-contribution is a repo/advanced feature) so a
 *  dedicated central never fails on a missing ~/.codex etc. Values come from central.env. */
export const STANDALONE_COMPOSE = `# Generated by \`agentop central\` — pulls the published central image (no repo needed).
# Managed file: re-created on each \`agentop central up\`. Edit central.env, not this file.
services:
  mongo:
    image: mongo:7
    command: --replSet rs0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "try { rs.status() } catch (e) { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'mongo:27017' }] }) }"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s
    # mongo is NOT published to the host — only the app service reaches it.
    volumes:
      - mongo_data:/data/db

  app:
    image: \${AGENTISTICS_IMAGE:-ghcr.io/blpsoares/agentistics:latest}
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGO_URL: \${MONGO_URL:-mongodb://mongo:27017/?replicaSet=rs0}
      MONGO_DB: \${MONGO_DB:-agentistics}
      AGENTISTICS_TEAM_CENTRAL: "1"
      AGENTISTICS_TEAM_ORG: \${AGENTISTICS_TEAM_ORG:-default}
      AGENTISTICS_TEAM_PASSWORD: \${AGENTISTICS_TEAM_PASSWORD:-}
      AGENTISTICS_TEAM_SESSION_SECRET: \${AGENTISTICS_TEAM_SESSION_SECRET:-}
      AGENTISTICS_TEAM_INGEST_TOKEN: \${AGENTISTICS_TEAM_INGEST_TOKEN:-}
      PORT: "47291"
      SERVE_STATIC: "1"
    ports:
      - "\${BIND_IP:-0.0.0.0}:\${APP_PORT:-48080}:47291"
    # Writable data dir (preferences, consolidate store). A named volume so it survives the
    # \`--force-recreate\` that every \`agentop central up\` does — otherwise the archive-mode
    # consent gate + install prompt reappear on every up.
    volumes:
      - agentistics_data:/root/.agentistics
    restart: unless-stopped

volumes:
  mongo_data:
  agentistics_data:
`

const hex = (bytes: number) => randomBytes(bytes).toString('hex')

export interface CentralEnvOpts {
  port?: string
  org?: string
  /** When omitted, a random password is generated. */
  password?: string
  /** When omitted, a random session secret is generated. */
  sessionSecret?: string
  ingestToken?: string
  bind?: string
  /** External Mongo connection string (Atlas/remote). When set, the central runs NATIVELY (no
   *  Docker, no bundled Mongo). When omitted, the bundled Docker Mongo service is used. */
  mongoUrl?: string
}

/** Connection string for the bundled Docker Mongo service (single-node replica set). */
export const BUNDLED_MONGO_URL = 'mongodb://mongo:27017/?replicaSet=rs0'

/** True when MONGO_URL targets the bundled Docker `mongo` service (→ run via Docker), as opposed
 *  to an external URI like Atlas (→ run natively, no Docker). Pure. */
export function isBundledMongo(mongoUrl: string): boolean {
  return /(?:\/\/|@)mongo:\d+/.test(mongoUrl)
}

/** Cheap validation that a string is a Mongo connection URI. Pure. */
export function looksLikeMongoUri(raw: string): boolean {
  return /^mongodb(\+srv)?:\/\/\S+/.test(raw.trim())
}

/**
 * Build the central.env contents (pure). Applies defaults (port 48080, org 'default',
 * bind 0.0.0.0) and auto-generates the admin password + session secret when not supplied.
 * Kept side-effect-free (except crypto randomness) so it is unit-testable.
 */
export function buildCentralEnv(opts: CentralEnvOpts = {}): string {
  const port = opts.port || '48080'
  const bind = opts.bind || '0.0.0.0'
  const org = opts.org || 'default'
  const password = opts.password || hex(24)
  const sessionSecret = opts.sessionSecret || hex(32)
  const ingest = opts.ingestToken ?? ''
  const mongoUrl = opts.mongoUrl?.trim() || BUNDLED_MONGO_URL
  return (
    `# agentistics Team Mode — generated by \`agentop central\`. Holds secrets; keep it private.\n` +
    `APP_PORT=${port}\n` +
    `BIND_IP=${bind}\n` +
    `MONGO_URL=${mongoUrl}\n` +
    `MONGO_DB=agentistics\n` +
    `AGENTISTICS_TEAM_CENTRAL=1\n` +
    `AGENTISTICS_TEAM_ORG=${org}\n` +
    `AGENTISTICS_TEAM_PASSWORD=${password}\n` +
    `AGENTISTICS_TEAM_SESSION_SECRET=${sessionSecret}\n` +
    `AGENTISTICS_TEAM_INGEST_TOKEN=${ingest}\n` +
    `AGENTISTICS_CENTRAL_USER=\n`
  )
}

/** docker compose for the standalone central, with project + env-file + compose-file pre-set. */
function composeArgs(envFile: string, composeFile: string, rest: string[]): string[] {
  return ['docker', 'compose', '-p', PROJECT, '--env-file', envFile, '-f', composeFile, ...rest]
}

async function runCompose(envFile: string, composeFile: string, rest: string[]): Promise<number> {
  try {
    const proc = Bun.spawn(composeArgs(envFile, composeFile, rest), {
      stdin: 'inherit',
      stdout: 'inherit',
      stderr: 'inherit',
      env: { ...process.env, AGENTISTICS_IMAGE: IMAGE },
    })
    return await proc.exited
  } catch (err) {
    process.stderr.write(
      `Could not run docker compose: ${err instanceof Error ? err.message : String(err)}\n` +
      'Is Docker installed and running?\n',
    )
    return 1
  }
}

/** Interactively generate central.env (secrets auto-filled). Called on first `up`, or `init`. */
async function initEnv(envFile: string): Promise<void> {
  process.stdout.write(`\nSetting up ${envFile} — press Enter to accept the [default] / auto-generate.\n\n`)
  const port = await input('Host port (APP_PORT)', { default: '48080' })
  const org = await input('Org name (AGENTISTICS_TEAM_ORG)', { default: 'default' })
  const passIn = await input('Admin password (Enter to auto-generate)', { default: '' })
  const password = passIn || hex(24)
  if (!passIn) process.stdout.write(`  -> generated password: ${password}\n`)
  const bind = await input('Bind IP (BIND_IP, blank = 0.0.0.0 all interfaces)', { default: '0.0.0.0' })

  // Database: bundled Docker Mongo, or an external URI (Atlas/remote) → runs natively, no Docker.
  const db = await select<'bundled' | 'external'>({
    message: 'Database',
    choices: [
      { name: 'Bundled Mongo (Docker starts it for you)', value: 'bundled' },
      { name: 'External URI — Atlas/remote (runs natively, no Docker)', value: 'external' },
    ],
  })
  let mongoUrl: string | undefined
  if (db === 'external') {
    for (;;) {
      const uri = await input('Mongo connection URI (mongodb+srv://…)', { default: '' })
      if (looksLikeMongoUri(uri)) { mongoUrl = uri.trim(); break }
      process.stdout.write('  Invalid URI — must start with mongodb:// or mongodb+srv://\n')
    }
    process.stdout.write('  -> external DB: the central will run natively (no Docker, no local Mongo).\n')
  }

  const env = buildCentralEnv({ port, org, password, bind, mongoUrl })
  await writeFile(envFile, env, 'utf-8')
  await chmod(envFile, 0o600).catch(() => {})
  process.stdout.write(
    `\nWrote ${envFile} (chmod 600).\n` +
    `  Keep the admin password — share it with your team to log in to the dashboard.\n\n`,
  )
}

/** Read a single KEY=value from central.env (no full dotenv parse needed). */
async function readEnvValue(envFile: string, key: string): Promise<string | undefined> {
  try {
    const text = await Bun.file(envFile).text()
    for (const line of text.split('\n')) {
      const m = line.match(new RegExp(`^${key}=(.*)$`))
      if (m) return m[1]
    }
  } catch { /* missing file */ }
  return undefined
}

/** Print the dashboard / central endpoint URL(s) after the central is up. */
async function printAccessUrl(envFile: string): Promise<void> {
  const port = (await readEnvValue(envFile, 'APP_PORT')) || '48080'
  const bind = (await readEnvValue(envFile, 'BIND_IP')) || '0.0.0.0'
  process.stdout.write('\nDashboard / central endpoint:\n')
  if (bind === '0.0.0.0' || bind === '') {
    process.stdout.write(`  local: http://localhost:${port}\n`)
    process.stdout.write('  Members connect to a reachable address of this host (LAN/Tailscale IP) on that port.\n')
  } else {
    process.stdout.write(`  http://${bind}:${port}\n`)
  }
}

/** Parse the KEY=value lines of a central.env into a map (ignores comments/blanks). */
async function loadEnvFile(envFile: string): Promise<Record<string, string>> {
  const out: Record<string, string> = {}
  try {
    const text = await Bun.file(envFile).text()
    for (const line of text.split('\n')) {
      if (!line || line.startsWith('#')) continue
      const eq = line.indexOf('=')
      if (eq === -1) continue
      out[line.slice(0, eq).trim()] = line.slice(eq + 1)
    }
  } catch { /* missing file → empty */ }
  return out
}

/**
 * Native central lifecycle (external DB → no Docker): the compiled binary IS the server, so we
 * re-invoke `agentop server` with the central env. It runs in the FOREGROUND; for a background
 * service use `agentop autostart central`. Docker-style down/logs/status don't apply here.
 */
async function runNativeCentral(envFile: string, action: CentralAction): Promise<number> {
  const env = await loadEnvFile(envFile)
  const port = env.APP_PORT || '48080'

  if (action !== 'up') {
    process.stdout.write(
      `\nThis central uses an EXTERNAL database, so it runs NATIVELY (no Docker).\n` +
      `  • start:   agentop central up            (foreground — Ctrl-C to stop)\n` +
      `  • service: agentop autostart central     (run it as a background service)\n`,
    )
    return 0
  }

  process.stdout.write(`\nStarting NATIVE central (external DB) on port ${port} …\n`)
  await printAccessUrl(envFile)
  process.stdout.write('  (running in the foreground — Ctrl-C to stop)\n\n')
  try {
    // Re-invoke this same binary as `agentop server`, but in central mode on APP_PORT. The child
    // reads MONGO_URL / password / secret / org from the central.env we pass through.
    const proc = Bun.spawn([process.execPath, 'server'], {
      env: { ...process.env, ...env, PORT: port, AGENTISTICS_TEAM_CENTRAL: '1', SERVE_STATIC: '1' } as Record<string, string>,
      stdin: 'inherit', stdout: 'inherit', stderr: 'inherit',
    })
    return await proc.exited
  } catch (err) {
    process.stderr.write(`Could not start native central: ${err instanceof Error ? err.message : String(err)}\n`)
    return 1
  }
}

/**
 * Standalone central lifecycle. With the bundled Mongo it materializes a compose and drives
 * `docker compose`; with an external DB (Atlas/remote) it runs the binary NATIVELY (no Docker).
 * Mirrors central.sh's commands.
 */
async function runCentralStandalone(action: CentralAction): Promise<number> {
  const envFile = join(STANDALONE_DIR, 'central.env')
  const composeFile = join(STANDALONE_DIR, 'docker-compose.yml')

  const isTTY = process.stdin.isTTY

  try {
    await mkdir(STANDALONE_DIR, { recursive: true })
  } catch (err) {
    process.stderr.write(`Could not prepare ${STANDALONE_DIR}: ${err instanceof Error ? err.message : String(err)}\n`)
    return 1
  }

  if (action === 'init') {
    if (!isTTY) { process.stderr.write('init needs an interactive terminal.\n'); return 1 }
    await initEnv(envFile)
    return 0
  }

  // On `up`, ensure central.env exists (prompt if TTY) BEFORE deciding Docker vs native.
  if (action === 'up') {
    if (!existsSync(envFile)) {
      if (!isTTY) { process.stderr.write(`${envFile} not found and stdin is not a TTY — run \`agentop central init\` first.\n`); return 1 }
      process.stdout.write(`${envFile} not found — let's create it.\n`)
      await initEnv(envFile)
    } else if (isTTY) {
      const rerun = await confirm(`${envFile} exists. Re-run interactive setup?`, false)
      if (rerun) await initEnv(envFile)
    }
  } else if (!existsSync(envFile)) {
    process.stderr.write(`No central configured yet at ${envFile}. Run \`agentop central up\` first.\n`)
    return 1
  }

  // External DB → run natively (no Docker); bundled → Docker compose.
  const mongoUrl = (await readEnvValue(envFile, 'MONGO_URL')) ?? ''
  if (!isBundledMongo(mongoUrl)) {
    return runNativeCentral(envFile, action)
  }

  try {
    await writeFile(composeFile, STANDALONE_COMPOSE, 'utf-8')
  } catch (err) {
    process.stderr.write(`Could not write ${composeFile}: ${err instanceof Error ? err.message : String(err)}\n`)
    return 1
  }

  if (action === 'up') {
    process.stdout.write(`\nStarting central from image ${IMAGE} …\n\n`)
    const code = await runCompose(envFile, composeFile, ['up', '-d', '--pull', 'always', '--force-recreate'])
    if (code === 0) {
      await runCompose(envFile, composeFile, ['ps'])
      await printAccessUrl(envFile)
    }
    return code
  }

  switch (action) {
    case 'restart': {
      const code = await runCompose(envFile, composeFile, ['restart', 'app'])
      if (code === 0) await printAccessUrl(envFile)
      return code
    }
    case 'logs':
      return runCompose(envFile, composeFile, ['logs', '-f', 'app'])
    case 'status':
      return runCompose(envFile, composeFile, ['ps'])
    case 'down':
      // No `-v` — the Mongo data volume is preserved.
      return runCompose(envFile, composeFile, ['down'])
    case 'pull': {
      const code = await runCompose(envFile, composeFile, ['pull'])
      if (code === 0) return runCompose(envFile, composeFile, ['up', '-d', '--force-recreate'])
      return code
    }
  }
  return 0
}
