/**
 * deploy.ts — pure helpers for Docker / autostart deployment generation.
 *
 * generateEnvFile(opts)  → .env file content string
 * autostartSnippet(platform, execPath) → shell/service snippet string
 *
 * These are pure functions with no side effects; they are tested in deploy.test.ts
 * and called by the GET /api/team/deploy route in index.ts.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface GenerateEnvFileOpts {
  /** Plain-text dashboard password (already generated by the caller) */
  password: string
  /** HMAC session-signing secret (already generated by the caller) */
  sessionSecret: string
  /** MongoDB connection string, e.g. mongodb://mongo:27017/?replicaSet=rs0 */
  mongoUrl: string
  /** MongoDB database name */
  mongoDb?: string
  /** Team organisation namespace */
  teamOrg?: string
  /** Ingest bearer token (optional) */
  ingestToken?: string
  /** Host port the app will listen on (default 47291) */
  appPort?: number
}

export type AutostartPlatform = 'systemd' | 'launchd' | 'pm2'

// ---------------------------------------------------------------------------
// generateEnvFile
// ---------------------------------------------------------------------------

/**
 * Returns the textual content of a `.env` file suitable for docker compose.
 * No secrets are logged — only the caller decides what to do with the string.
 */
export function generateEnvFile(opts: GenerateEnvFileOpts): string {
  const {
    password,
    sessionSecret,
    mongoUrl,
    mongoDb = 'agentistics',
    teamOrg = 'default',
    ingestToken = '',
    appPort = 47291,
  } = opts

  const lines: string[] = [
    '# agentistics Team Mode — generated .env',
    '# Keep this file private. Never commit it to version control.',
    '',
    `APP_PORT=${appPort}`,
    '',
    '# MongoDB',
    `MONGO_URL=${mongoUrl}`,
    `MONGO_DB=${mongoDb}`,
    '',
    '# Team mode',
    'AGENTISTICS_TEAM_CENTRAL=1',
    `AGENTISTICS_TEAM_ORG=${teamOrg}`,
    '',
    '# Auth',
    `AGENTISTICS_TEAM_PASSWORD=${password}`,
    `AGENTISTICS_TEAM_SESSION_SECRET=${sessionSecret}`,
    '',
    '# Ingest token (leave empty to allow unauthenticated ingestion)',
    `AGENTISTICS_TEAM_INGEST_TOKEN=${ingestToken}`,
  ]

  return lines.join('\n') + '\n'
}

// ---------------------------------------------------------------------------
// autostartSnippet
// ---------------------------------------------------------------------------

/**
 * Returns a platform-specific autostart snippet as a string.
 *
 * @param platform - 'systemd' | 'launchd' | 'pm2'
 * @param execPath - absolute path to the agentop binary (or 'docker compose up -d' command)
 */
export function autostartSnippet(platform: AutostartPlatform, execPath: string): string {
  switch (platform) {
    case 'systemd':
      return [
        '# /etc/systemd/system/agentistics.service',
        '[Unit]',
        'Description=agentistics Team Dashboard',
        'After=network.target docker.service',
        'Requires=docker.service',
        '',
        '[Service]',
        'Type=simple',
        'WorkingDirectory=/opt/agentistics',
        `ExecStart=${execPath}`,
        'Restart=on-failure',
        'RestartSec=5',
        'StandardOutput=journal',
        'StandardError=journal',
        '',
        '[Install]',
        'WantedBy=multi-user.target',
        '',
        '# Enable and start:',
        '#   sudo systemctl daemon-reload',
        '#   sudo systemctl enable --now agentistics',
      ].join('\n')

    case 'launchd':
      return [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"',
        '  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
        '<plist version="1.0">',
        '<dict>',
        '  <key>Label</key>',
        '  <string>com.agentistics.team</string>',
        '  <key>ProgramArguments</key>',
        '  <array>',
        `    <string>${execPath}</string>`,
        '  </array>',
        '  <key>RunAtLoad</key>',
        '  <true/>',
        '  <key>KeepAlive</key>',
        '  <true/>',
        '  <key>StandardOutPath</key>',
        '  <string>/tmp/agentistics.log</string>',
        '  <key>StandardErrorPath</key>',
        '  <string>/tmp/agentistics.err</string>',
        '</dict>',
        '</plist>',
        '',
        '# Save to ~/Library/LaunchAgents/com.agentistics.team.plist, then:',
        '#   launchctl load ~/Library/LaunchAgents/com.agentistics.team.plist',
      ].join('\n')

    case 'pm2':
      return [
        '# ecosystem.config.cjs',
        'module.exports = {',
        '  apps: [{',
        "    name: 'agentistics',",
        `    script: '${execPath}',`,
        '    restart_delay: 5000,',
        "    env: { NODE_ENV: 'production' },",
        '  }],',
        '}',
        '',
        '# Start / save:',
        '#   pm2 start ecosystem.config.cjs',
        '#   pm2 save',
        '#   pm2 startup   # follow the printed command',
      ].join('\n')
  }
}
