#!/usr/bin/env bun
/**
 * Creates a minimal type stub for src/embedded-dist.generated.ts if the file
 * does not already exist. Allows `bun tsc --noEmit` and `bun test` to run in
 * environments where the full Vite build hasn't been executed yet (CI, fresh
 * clone, pre-commit hooks).
 *
 * The real file is generated by `bun run build:assets` (scripts/embed-dist.ts)
 * and is listed in .gitignore — never commit it.
 */

import { existsSync } from 'fs'
import { writeFileSync } from 'fs'
import { join } from 'path'

const ROOT = new URL('..', import.meta.url).pathname
const out = join(ROOT, 'src', 'embedded-dist.generated.ts')

if (!existsSync(out)) {
  writeFileSync(
    out,
    [
      '// Type stub — real file generated by `bun run build:assets`.',
      "export type EmbeddedAsset = { content: string; contentType: string; encoding: 'utf8' | 'base64' }",
      'export const embeddedDist: Record<string, EmbeddedAsset> = {}',
      '',
    ].join('\n'),
  )
  process.stdout.write(`created type stub: src/embedded-dist.generated.ts\n`)
}
